### ISSUE TITLE
Client read large packet

### ISSUE THREAD

**Issue by morefreeze** [pingcap/ticlient#6]
Client read large packet(>10KB) need read multi time. Refer to https://github.com/c4pt0r/go-hbase/blob/master/conn.go#L72

**Comment by siddontang** [comment]
why not read into a buffer directly?

**Comment by morefreeze** [comment]
@siddontang I have done read into buffer, but it seems can't read whole payload once. I need change it just kvserver, I think.

**Comment by disksing** [comment]
Does #10 fix this issue? @morefreeze

**Comment by siddontang** [comment]
I think it can.

**Comment by morefreeze** [comment]
You can change scan batch size to 1000 or more, then run store_test to see error occur or not.
